/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class chapter_detail_req_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("chapter_detail_req_t");
    private static const CHAPTER_ID_FIELD_DESC:TField = new TField("chapter_id", TType.I32, 1);

    private var _chapter_id:int;
    public static const CHAPTER_ID:int = 1;

    private var __isset_chapter_id:Boolean = false;

    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[CHAPTER_ID] = new FieldMetaData("chapter_id", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32));
    }
    {
      FieldMetaData.addStructMetaDataMap(chapter_detail_req_t, metaDataMap);
    }

    public function chapter_detail_req_t() {
      this._chapter_id = 0;
    }

    public function get chapter_id():int {
      return this._chapter_id;
    }

    public function set chapter_id(chapter_id:int):void {
      this._chapter_id = chapter_id;
      this.__isset_chapter_id = true;
    }

    public function unsetChapter_id():void {
      this.__isset_chapter_id = false;
    }

    // Returns true if field chapter_id is set (has been assigned a value) and false otherwise
    public function isSetChapter_id():Boolean {
      return this.__isset_chapter_id;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case CHAPTER_ID:
        if (value == null) {
          unsetChapter_id();
        } else {
          this.chapter_id = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case CHAPTER_ID:
        return this.chapter_id;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case CHAPTER_ID:
        return isSetChapter_id();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case CHAPTER_ID:
            if (field.type == TType.I32) {
              this.chapter_id = iprot.readI32();
              this.__isset_chapter_id = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CHAPTER_ID_FIELD_DESC);
      oprot.writeI32(this.chapter_id);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("chapter_detail_req_t(");
      var first:Boolean = true;

      ret += "chapter_id:";
      ret += this.chapter_id;
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
