/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class client_cmd_e   {
    public static const LOGIN_REQ:int = 1;
    public static const CHAT_REQ:int = 2;

    public static const VALID_VALUES:Set = new Set(LOGIN_REQ, CHAT_REQ);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[LOGIN_REQ] = "LOGIN_REQ";
      VALUES_TO_NAMES[CHAT_REQ] = "CHAT_REQ";

    }
  }
}
