/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class server_cmd_e   {
    public static const LOGIN_RET:int = 1;
    public static const CHAT_RET:int = 2;
    public static const ERROR_CODE_RET:int = 3;
    public static const START_ROUND_RET:int = 4;
    public static const NEXT_WORD_RET:int = 5;
    public static const END_ROUND_RET:int = 6;
    public static const USER_PROPERTY_RET:int = 7;
    public static const PACK_INFO_RET:int = 8;
    public static const FRIEND_INFO_RET:int = 9;
    public static const GAME_INFO_RET:int = 10;
    public static const TASK_INFO_RET:int = 11;
    public static const CHAPTER_DETAIL_RET:int = 12;
    public static const TASK_COMPLETED_RET:int = 13;
    public static const NOTIFY_ADD_FRIEND_RET:int = 14;
    public static const ADD_FRIEND_SUCCESS_RET:int = 15;
    public static const DEL_FRIEND_RET:int = 16;
    public static const UPDATE_PROPERTY_RET:int = 17;

    public static const VALID_VALUES:Set = new Set(LOGIN_RET, CHAT_RET, ERROR_CODE_RET, START_ROUND_RET, NEXT_WORD_RET, END_ROUND_RET, USER_PROPERTY_RET, PACK_INFO_RET, FRIEND_INFO_RET, GAME_INFO_RET, TASK_INFO_RET, CHAPTER_DETAIL_RET, TASK_COMPLETED_RET, NOTIFY_ADD_FRIEND_RET, ADD_FRIEND_SUCCESS_RET, DEL_FRIEND_RET, UPDATE_PROPERTY_RET);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[LOGIN_RET] = "LOGIN_RET";
      VALUES_TO_NAMES[CHAT_RET] = "CHAT_RET";
      VALUES_TO_NAMES[ERROR_CODE_RET] = "ERROR_CODE_RET";
      VALUES_TO_NAMES[START_ROUND_RET] = "START_ROUND_RET";
      VALUES_TO_NAMES[NEXT_WORD_RET] = "NEXT_WORD_RET";
      VALUES_TO_NAMES[END_ROUND_RET] = "END_ROUND_RET";
      VALUES_TO_NAMES[USER_PROPERTY_RET] = "USER_PROPERTY_RET";
      VALUES_TO_NAMES[PACK_INFO_RET] = "PACK_INFO_RET";
      VALUES_TO_NAMES[FRIEND_INFO_RET] = "FRIEND_INFO_RET";
      VALUES_TO_NAMES[GAME_INFO_RET] = "GAME_INFO_RET";
      VALUES_TO_NAMES[TASK_INFO_RET] = "TASK_INFO_RET";
      VALUES_TO_NAMES[CHAPTER_DETAIL_RET] = "CHAPTER_DETAIL_RET";
      VALUES_TO_NAMES[TASK_COMPLETED_RET] = "TASK_COMPLETED_RET";
      VALUES_TO_NAMES[NOTIFY_ADD_FRIEND_RET] = "NOTIFY_ADD_FRIEND_RET";
      VALUES_TO_NAMES[ADD_FRIEND_SUCCESS_RET] = "ADD_FRIEND_SUCCESS_RET";
      VALUES_TO_NAMES[DEL_FRIEND_RET] = "DEL_FRIEND_RET";
      VALUES_TO_NAMES[UPDATE_PROPERTY_RET] = "UPDATE_PROPERTY_RET";

    }
  }
}
